kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nodejs-jenkins-pipeline
  namespace: carlos-roberto-devops-dev
  uid: adc12858-cacd-4dfd-846d-d64d7c4cfe5c
  resourceVersion: '1420279596'
  generation: 0
  creationTimestamp: '2022-06-22T21:07:06Z'
spec:
  nodeSelector:
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile:
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/carlosrobertodevops/nextjs-optydev-io-xyz.git'
  runPolicy: Serial
status:
  lastVersion: 0
